### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by zoobab** [phdussud/pico-dirtyJtag#1]
I am trying to build your firmware with pico-sdk, and I hit the following error:

```
[ 26%] Building C object CMakeFiles/dirtyJtag.dir/get_serial.c.obj
In file included from /code/pico-dirtyJtag/get_serial.c:27:
/code/pico-sdk/src/rp2_common/pico_unique_id/include/pico/unique_id.h:72:52: error: unknown type name 'uint'; did you mean 'int'?
   72 | void pico_get_unique_board_id_string(char *id_out, uint len);
      |                                                    ^~~~
      |                                                    int
make[2]: *** [CMakeFiles/dirtyJtag.dir/build.make:102: CMakeFiles/dirtyJtag.dir/get_serial.c.obj] Error 1
make[2]: Leaving directory '/code/pico-dirtyJtag/build'
```

I am using pico-sdk version 1.2.0 (bfcbefafc5d2a210551a4d9d80b4303d4ae0adf7).

**Comment by phdussud** [comment]
Interesting. This error does not appear with an older (1.1) version of the SDK. We need a work around...
Thanks,
Patrick.
________________________________
From: Benjamin Henrion ***@***.***>
Sent: Saturday, June 5, 2021 3:44 AM
To: phdussud/pico-dirtyJtag ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [phdussud/pico-dirtyJtag] Build error (#1)


I am trying to build your firmware with pico-sdk, and I hit the following error:

[ 26%] Building C object CMakeFiles/dirtyJtag.dir/get_serial.c.obj
In file included from /code/pico-dirtyJtag/get_serial.c:27:
/code/pico-sdk/src/rp2_common/pico_unique_id/include/pico/unique_id.h:72:52: error: unknown type name 'uint'; did you mean 'int'?
   72 | void pico_get_unique_board_id_string(char *id_out, uint len);
      |                                                    ^~~~
      |                                                    int
make[2]: *** [CMakeFiles/dirtyJtag.dir/build.make:102: CMakeFiles/dirtyJtag.dir/get_serial.c.obj] Error 1
make[2]: Leaving directory '/code/pico-dirtyJtag/build'


I am using pico-sdk version 1.2.0 (bfcbefafc5d2a210551a4d9d80b4303d4ae0adf7).

**Comment by phdussud** [comment]
I think gcc does not define uint anymore. 
The fix would be to define it right before the failing include in get_serial.c like so(change in bold)
**typedef unsigned int uint;**
#include "pico/unique_id.h"

**Comment by phdussud** [comment]
I updated with the version 1.2 of the sdk and it builds with the change. I haven't tested the resulting binary yet.

**Comment by phdussud** [comment]
A better fix is to replace 
#include <stdint.h>  by #include "pico/types.h". This header file defined uint the same way I indicated. 

This will give us:
#include "pico/types.h"
#include "pico/unique_id.h"

**Comment by phdussud** [comment]
I committed a fix.
