### ISSUE TITLE
add secondary UART interface

### ISSUE THREAD

**Issue by luyi1888** [phdussud/pico-dirtyJtag#15]
Hi,
I need to use the both of UART on the pico. So i modified the code.
Can i submit a pull request?

**Comment by phdussud** [comment]
Sure, please do. @jeanthom do you agree?

**Comment by luyi1888** [comment]
#16 
I only have the Pico-like board. So the config for other boards may need add by other contributor.
I left the 1 UART for those boards for now.

**Comment by phdussud** [comment]
Done
