### ISSUE TITLE
Can't flash XSVF files and SVF files with more than 58kb.

### ISSUE THREAD

**Issue by chackAJMCPE** [phdussud/pico-dirtyJtag#18]
Same as title. Help me fix it or fix the code PLEASE. It's SUPER IMPORTANT.

**Comment by phdussud** [comment]
What app are you using to flash? Poor connection between the pico board and the  FPGA could also be the issue. You can try a lower clock rate and /or better connection like shielded wires.

**Comment by phdussud** [comment]
Hopefully, a better connection did the trick.
