### ISSUE TITLE
bsp/board.h no such file or directory

### ISSUE THREAD

**Issue by dontdeadopeninside** [phdussud/pico-dirtyJtag#8]
dirtyjtag.c:7:10

**Comment by phdussud** [comment]
This file is part of the [pico_sdk](https://github.com/raspberrypi/pico-sdk) This app is coded according to the sdk rules. I just verified that it builds without error or warning using the sdk version 1.40 
Please refer to this [guide](https://www.raspberrypi.com/documentation/microcontrollers/c_sdk.html).

**Comment by phdussud** [comment]
I have just created a release if you just want to use this project without having to build it first
